// Get job by ID
let jobs = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'TechCorp Inc.',
    location: 'San Francisco, CA',
    type: 'Full-time',
    category: 'Engineering',
    salary: '$120k - $180k',
    description: 'We are looking for an experienced Frontend Developer to join our team. You will be responsible for building user interfaces using React and Next.js. The ideal candidate has a passion for creating beautiful, performant web applications.',
    requirements: ['5+ years of experience', 'React/Next.js expertise', 'TypeScript proficiency', 'Team leadership experience'],
    badges: ['Remote', 'Urgent', 'Featured'],
    postedDate: '2026-02-03',
    companyLogo: null,
  },
  {
    id: '2',
    title: 'Product Designer',
    company: 'DesignStudio',
    location: 'New York, NY',
    type: 'Full-time',
    category: 'Design',
    salary: '$90k - $130k',
    description: 'Join our creative team as a Product Designer. You will work on exciting projects for Fortune 500 clients.',
    requirements: ['3+ years of product design', 'Figma expertise', 'Strong portfolio', 'UX research skills'],
    badges: ['Hybrid', 'Benefits'],
    postedDate: '2026-02-02',
    companyLogo: null,
  },
  {
    id: '3',
    title: 'Backend Engineer',
    company: 'DataFlow Systems',
    location: 'Austin, TX',
    type: 'Full-time',
    category: 'Engineering',
    salary: '$130k - $170k',
    description: 'Build scalable backend systems using Node.js and Python. Work with our data infrastructure team.',
    requirements: ['4+ years backend experience', 'Node.js/Python', 'Database design', 'API development'],
    badges: ['Remote', 'Stock Options'],
    postedDate: '2026-02-01',
    companyLogo: null,
  },
  {
    id: '4',
    title: 'Marketing Manager',
    company: 'GrowthHub',
    location: 'Los Angeles, CA',
    type: 'Full-time',
    category: 'Marketing',
    salary: '$80k - $110k',
    description: 'Lead our marketing efforts and drive brand awareness. Manage campaigns across multiple channels.',
    requirements: ['5+ years marketing experience', 'Digital marketing expertise', 'Team management', 'Analytics skills'],
    badges: ['On-site', 'Leadership'],
    postedDate: '2026-01-30',
    companyLogo: null,
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    company: 'CloudNative Co.',
    location: 'Seattle, WA',
    type: 'Contract',
    category: 'Engineering',
    salary: '$100/hr',
    description: 'Help us build and maintain our cloud infrastructure. Experience with AWS and Kubernetes required.',
    requirements: ['AWS/GCP expertise', 'Kubernetes', 'CI/CD pipelines', 'Infrastructure as Code'],
    badges: ['Remote', 'Contract'],
    postedDate: '2026-01-28',
    companyLogo: null,
  },
  {
    id: '6',
    title: 'UX Researcher',
    company: 'UserFirst Labs',
    location: 'Boston, MA',
    type: 'Part-time',
    category: 'Design',
    salary: '$50/hr',
    description: 'Conduct user research and usability testing. Help shape product decisions with data-driven insights.',
    requirements: ['UX research experience', 'Qualitative research methods', 'Data analysis', 'Communication skills'],
    badges: ['Hybrid', 'Flexible Hours'],
    postedDate: '2026-01-25',
    companyLogo: null,
  },
  {
    id: '7',
    title: 'Sales Representative',
    company: 'SalesForce Pro',
    location: 'Chicago, IL',
    type: 'Full-time',
    category: 'Sales',
    salary: '$60k + Commission',
    description: 'Drive B2B sales and build lasting client relationships. Uncapped commission potential.',
    requirements: ['2+ years B2B sales', 'CRM experience', 'Strong communication', 'Goal-oriented'],
    badges: ['On-site', 'Commission'],
    postedDate: '2026-01-22',
    companyLogo: null,
  },
  {
    id: '8',
    title: 'Data Scientist',
    company: 'AI Innovations',
    location: 'Remote',
    type: 'Full-time',
    category: 'Data Science',
    salary: '$140k - $200k',
    description: 'Build ML models and derive insights from large datasets. Work on cutting-edge AI projects.',
    requirements: ['ML/AI expertise', 'Python/R proficiency', 'Statistics background', 'PhD preferred'],
    badges: ['Remote', 'Featured', 'Top Salary'],
    postedDate: '2026-02-04',
    companyLogo: null,
  },
];

export async function GET(request, { params }) {
  const { id } = await params;
  const job = jobs.find(j => j.id === id);
  
  if (!job) {
    return Response.json({ error: 'Job not found' }, { status: 404 });
  }
  
  return Response.json({ job });
}
